apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redisCart.name }}
  labels:
    app: {{ .Values.redisCart.name }}
spec:
  replicas: {{ .Values.redisCart.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.redisCart.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.redisCart.name }}
    spec:
      containers:
        - image: {{ .Values.redisCart.image }}
          name: {{ .Values.redisCart.name }}
          ports:
            - containerPort: {{ .Values.redisCart.port }}
          volumeMounts:
            - mountPath: {{ .Values.redisCart.volume.mountPath }}
              name: redis-data
          readinessProbe:
            tcpSocket:
              port: {{ .Values.redisCart.port }}
            periodSeconds: 10
            initialDelaySeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            tcpSocket:
              port: {{ .Values.redisCart.port }}
            periodSeconds: 10
            initialDelaySeconds: 15
            timeoutSeconds: 3
          resources:
            requests:
              memory: {{ .Values.redisCart.resources.requests.memory }}
              cpu: {{ .Values.redisCart.resources.requests.cpu }}
            limits:
              memory: {{ .Values.redisCart.resources.limits.memory }}
              cpu: {{ .Values.redisCart.resources.limits.cpu }}
      volumes:
        - name: redis-data
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redisCart.serviceName }}
  labels:
    app: {{ .Values.redisCart.name }}
spec:
  selector:
    app: {{ .Values.redisCart.name }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.redisCart.port }}
      targetPort: {{ .Values.redisCart.port }}
