adservice: 
  enabled: true
  name: adservice
  replicas: 2
  image: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice:v0.10.4
  port: 9555
  resources:
    requests:
      memory: 200Mi  
      cpu: 180m
    limits:
      memory: 300Mi
      cpu: 300m
  serviceName: ad-service

cartservice: 
  enabled: true
  name: cartservice
  replicas: 2
  image: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice:v0.10.4
  port: 7070
  redisAddr: redis-cart:6379
  resources:
    requests:
      memory: 64Mi  
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 200m
  serviceName: cart-service

---

checkoutservice: 
  enabled: true
  name: checkoutservice
  replicas: 2
  image: us-central1-docker.pkg.dev/google-samples/microservices-demo/checkoutservice:v0.10.4
  port: 5050
  resources:
    requests:
      memory: 64Mi  
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 200m
  serviceName: checkout-service

---

currencyservice: 
  enabled: true
  name: currencyservice
  replicas: 2
  image: us-central1-docker.pkg.dev/google-samples/microservices-demo/currencyservice:v0.10.4
  disableProfiler: true
  port: 7000
  resources:
    requests:
      memory: 64Mi  
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 200m
  serviceName: currency-service

---

emailservice: 
  enabled: true
  name: emailservice
  replicas: 2
  image: us-central1-docker.pkg.dev/google-samples/microservices-demo/emailservice:v0.10.4
  port: 8080
  resources:
    requests:
      memory: 64Mi  
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 200m
  serviceName: email-service

---

paymentservice: 
  enabled: true
  name: paymentservice
  replicas: 2
  image: us-central1-docker.pkg.dev/google-samples/microservices-demo/paymentservice:v0.10.4
  disableProfiler: true
  port: 50051
  resources:
    requests:
      memory: 64Mi  
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 200m
  serviceName: payment-service

---

productcatalogservice: 
  enabled: true
  name: productcatalogservice
  replicas: 2
  image: us-central1-docker.pkg.dev/google-samples/microservices-demo/productcatalogservice:v0.10.4
  port: 3550
  resources:
    requests:
      memory: 64Mi  
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 200m
  serviceName: productcatalog-service

---

recommendationservice: 
  enabled: true
  name: recommendationservice
  replicas: 2
  image: us-central1-docker.pkg.dev/google-samples/microservices-demo/recommendationservice:v0.10.4
  port: 8080
  resources:
    requests:
      memory: 64Mi  
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 200m
  serviceName: recommendation-service

---

shoppingservice:
  name: shoppingassistantservice
  port: 80

---

shippingservice: 
  enabled: true
  name: shippingservice
  replicas: 2
  image: us-central1-docker.pkg.dev/google-samples/microservices-demo/shippingservice:v0.10.4
  port: 50051
  resources:
    requests:
      memory: 64Mi  
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 200m
  serviceName: shipping-service

---

frontend: 
  name: frontend
  replicas: 2
  image: us-central1-docker.pkg.dev/google-samples/microservices-demo/frontend:v0.10.4
  port: 8080
  resources:
    requests:
      memory: 64Mi  
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 200m
  serviceName: frontend-service

---

redisCart: 
  name: redis-cart
  replicas: 2
  image: redis:8.4.0-alpine
  port: 6379
  resources:
    requests:
      memory: 200Mi  
      cpu: 125m
    limits:
      memory: 256Mi
      cpu: 200m
  volume:
    mountPath: /data
  serviceName: rediscart-service