apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  namespace: microservices-demo
  labels:
    app: checkoutservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/google-samples/microservices-demo/checkoutservice:v0.10.4
          name: checkoutservice
          ports:
            - containerPort: 5050
          env:
            - name: PORT
              value: "5050"
            - name: SHIPPING_SERVICE_ADDR
              value: "shippingservice:50051"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "productcatalogservice:3550"
            - name: CART_SERVICE_ADDR
              value: "cartservice:7070"
            - name: CURRENCY_SERVICE_ADDR
              value: "currencyservice:7000"
            - name: EMAIL_SERVICE_ADDR
              value: "emailservice:5000"
            - name: PAYMENT_SERVICE_ADDR
              value: "paymentservice:50051"
          readinessProbe:
            grpc:
              port: 5050
            periodSeconds: 12
            initialDelaySeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            grpc:
              port: 5050
            periodSeconds: 12
            initialDelaySeconds: 15
            timeoutSeconds: 3
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
