{{- if .Values.adservice.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.adservice.name }}
  labels:
    app: {{ .Values.adservice.name }}
spec:
  replicas: {{ .Values.adservice.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.adservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.adservice.name }}
    spec:
      containers:
        - image: {{ .Values.adservice.image }}
          name: {{ .Values.adservice.name }}
          ports:
            - containerPort: {{ .Values.adservice.port }}
          env:
            - name: PORT
              value: "{{ .Values.adservice.port }}"
          readinessProbe:
            grpc:
              port: {{ .Values.adservice.port }}
            periodSeconds: 12
            initialDelaySeconds: 15
            timeoutSeconds: 3
          livenessProbe:
            grpc:
              port: {{ .Values.adservice.port }}
            periodSeconds: 12
            initialDelaySeconds: 25
            timeoutSeconds: 3
          resources:
            requests:
              memory: {{ .Values.adservice.resources.requests.memory }}
              cpu: {{ .Values.adservice.resources.requests.cpu }}
            limits:
              memory: {{ .Values.adservice.resources.limits.memory }}
              cpu: {{ .Values.adservice.resources.limits.cpu }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.adservice.serviceName }}
  labels:
    app: {{ .Values.adservice.name }}
spec:
  selector:
    app: {{ .Values.adservice.name }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.adservice.port }}
      targetPort: {{ .Values.adservice.port }}

{{- end }}