{{- if .Values.cartservice.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cartservice.name }}
  labels:
    app: {{ .Values.cartservice.name }}
spec:
  replicas: {{ .Values.cartservice.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.cartservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.cartservice.name }}
    spec:
      containers:
        - image: {{ .Values.cartservice.image }}
          name: {{ .Values.cartservice.name }}
          ports:
            - containerPort: {{ .Values.cartservice.port }}
          env:
            - name: PORT
              value: "{{ .Values.cartservice.port }}"
            - name: REDIS_ADDR
              value: "redis-cart:6379"
          readinessProbe:
            grpc:
              port: {{ .Values.cartservice.port }}
            periodSeconds: 12
            initialDelaySeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            grpc:
              port: {{ .Values.cartservice.port }}
            periodSeconds: 12
            initialDelaySeconds: 15
            timeoutSeconds: 3
          resources:
            requests:
              memory: {{ .Values.cartservice.resources.requests.memory }}
              cpu: {{ .Values.cartservice.resources.requests.cpu }}
            limits:
              memory: {{ .Values.cartservice.resources.limits.memory }}
              cpu: {{ .Values.cartservice.resources.limits.cpu }}

--- 

apiVersion: v1
kind: Service
metadata:
  name: cartservice
  labels:
    app: {{ .Values.cartservice.name }}
spec:
  selector:
    app: {{ .Values.cartservice.name }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.cartservice.port }}
      targetPort: {{ .Values.cartservice.port }}

{{- end }}