{{- if .Values.currencyservice.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.currencyservice.name }}
  labels:
    app: {{ .Values.currencyservice.name }}
spec:
  replicas: {{ .Values.currencyservice.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.currencyservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.currencyservice.name }}
    spec:
      containers:
        - image: {{ .Values.currencyservice.image }}
          name: {{ .Values.currencyservice.name }}
          ports:
            - containerPort: {{ .Values.currencyservice.port }}
          env:
            - name: PORT
              value: "{{ .Values.currencyservice.port }}"
            - name: "DISABLE_PROFILER"
              value: "{{ .Values.currencyservice.disableProfiler }}"
          readinessProbe:
            grpc:
              port: {{ .Values.currencyservice.port }}
            periodSeconds: 12
            initialDelaySeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            grpc:
              port: {{ .Values.currencyservice.port }}
            periodSeconds: 12
            initialDelaySeconds: 15
            timeoutSeconds: 3
          resources:
            requests:
              memory: {{ .Values.currencyservice.resources.requests.memory }}
              cpu: {{ .Values.currencyservice.resources.requests.cpu }}
            limits:
              memory: {{ .Values.currencyservice.resources.limits.memory }}
              cpu: {{ .Values.currencyservice.resources.limits.cpu }}

---

apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  labels:
    app: {{ .Values.currencyservice.name }}
spec:
  selector:
    app: {{ .Values.currencyservice.name }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.currencyservice.port }}
      targetPort: {{ .Values.currencyservice.port }}

{{- end }}