{{- if .Values.emailservice.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.emailservice.name }}
  labels:
    app: {{ .Values.emailservice.name }}
spec:
  replicas: {{ .Values.emailservice.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.emailservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.emailservice.name }}
    spec:
      containers:
        - image: {{ .Values.emailservice.image }}
          name: {{ .Values.emailservice.name }}
          env:
            - name: PORT
              value: "{{ .Values.emailservice.port }}"
          readinessProbe:
            grpc:
              port: {{ .Values.emailservice.port }}
            periodSeconds: 12
            initialDelaySeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            grpc:
              port: {{ .Values.emailservice.port }}
            periodSeconds: 12
            initialDelaySeconds: 15
            timeoutSeconds: 3
          resources:
            requests:
              memory: {{ .Values.emailservice.resources.requests.memory }}
              cpu: {{ .Values.emailservice.resources.requests.cpu }}
            limits:
              memory: {{ .Values.emailservice.resources.limits.memory }}
              cpu: {{ .Values.emailservice.resources.limits.cpu }}
---

apiVersion: v1
kind: Service
metadata:
  name: emailservice
  labels:
    app: {{ .Values.emailservice.name }}
spec:
  selector:
    app: {{ .Values.emailservice.name }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: {{ .Values.emailservice.port }}

{{- end }}