{{- if .Values.recommendationservice.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.recommendationservice.name }}
  labels:
    app: {{ .Values.recommendationservice.name }}
spec:
  replicas: {{ .Values.recommendationservice.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.recommendationservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.recommendationservice.name }}
    spec:
      containers:
        - image: {{ .Values.recommendationservice.image }}
          name: {{ .Values.recommendationservice.name }}
          env:
            - name: PORT
              value: "{{ .Values.recommendationservice.port }}"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "{{ .Values.productcatalogservice.name }}:{{ .Values.productcatalogservice.port }}"
          readinessProbe:
            grpc:
              port: {{ .Values.recommendationservice.port }}
            periodSeconds: 12
            initialDelaySeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            grpc:
              port: {{ .Values.recommendationservice.port }}
            periodSeconds: 12
            initialDelaySeconds: 15
            timeoutSeconds: 3
          resources:
            requests:
              memory: {{ .Values.recommendationservice.resources.requests.memory }}
              cpu: {{ .Values.recommendationservice.resources.requests.cpu }}
            limits:
              memory: {{ .Values.recommendationservice.resources.limits.memory }}
              cpu: {{ .Values.recommendationservice.resources.limits.cpu }}
---

apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  labels:
    app: {{ .Values.recommendationservice.name }}
spec:
  selector:
    app: {{ .Values.recommendationservice.name }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.recommendationservice.port }}
      targetPort: {{ .Values.recommendationservice.port }}

{{- end }}