apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  namespace: microservices-demo
  labels:
    app: productcatalogservice
spec:
  selector:
    app: productcatalogservice
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3550
      targetPort: 3550
